import {
  LayoutDashboard,
  UserRoundCog,
  BookOpenCheck,
  FileSpreadsheet,
  RotateCcw,
  Users,
  Activity,
  Wallet,
  UserPlus,
  Settings,
  LogOut,
  UnfoldHorizontal,
} from "lucide-react";

import {
  academicRoutes,
  additionalFeeRoutes,
  adminRoutes,
  announcementRoutes,
  dashboardRoutes,
  electionRoutes,
  eventRoutes,
  examRoutes,
  financialRoutes,
  registrationFeeRoutes,
  resitFeeRoutes,
  resitRoutes,
  schoolActivities,
  schoolExpenseRoutes,
  settingRoutes,
  StudentRoutes,
  tuitionFeeRoutes,
  teacherRoutes,
  hallRoutes,
  activationCodeRoutes,
  courseRoutes,
} from "../../utils/paths";

export const sidebarItems = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    path: "/",
    routes: dashboardRoutes,
    isParent: false,
  },
  {
    id: "administrator",
    label: "Administrator",
    icon: UserRoundCog,
    path: "/school-admins",
    routes: adminRoutes,
    isParent: true,
    children: [
      {
        id: "school-admins",
        label: "School Admins",
        path: "/school-admins",
        routes: adminRoutes,
      },
      {
        id: "departments",
        label: "Departments",
        path: "/departments",
        routes: adminRoutes,
      },
      {
        id: "specialties",
        label: "Specialties",
        path: "/specialties",
        routes: adminRoutes,
      },
      {
        id: "teacher",
        label: "Teacher",
        path: "/teacher",
        routes: teacherRoutes,
      },
      { id: "halls", label: "Halls", path: "/hall", routes: hallRoutes },
    ],
  },
  {
    id: "academics",
    label: "Academics",
    icon: BookOpenCheck,
    path: "/grades-configuration",
    routes: academicRoutes,
    isParent: true,
    children: [
      {
        id: "grades-scale",
        label: "Grades Scale",
        path: "/grades-configuration",
        routes: academicRoutes,
      },
      {
        id: "semesters",
        label: "Semester",
        path: "/semesters",
        routes: academicRoutes,
      },
      {
        id: "academic-year",
        label: "Academic Year",
        path: "/academic-year",
        routes: academicRoutes,
      },
      {
        id: "courses",
        label: "Courses",
        path: "/courses",
        routes: courseRoutes,
      },
      {
        id: "time-table",
        label: "Time-table",
        path: "/time-table",
        routes: academicRoutes,
      },
    ],
  },
  {
    id: "manage-exams",
    label: "Manage Exams",
    icon: FileSpreadsheet,
    path: "/exam",
    routes: examRoutes,
    isParent: true,
    children: [
      { id: "exam", label: "Exam", path: "/exam", routes: examRoutes },
      {
        id: "exam-candidate",
        label: "Exam Candidate",
        path: "/exam-candidate",
        routes: examRoutes,
      },
      {
        id: "exam-timetable",
        label: "Exam Timetable",
        path: "/exam-timetable",
        routes: examRoutes,
      },
      {
        id: "exam-results",
        label: "Exam Results",
        path: "/exam-results",
        routes: examRoutes,
      },
    ],
  },
  {
    id: "manage-resit",
    label: "Manage Resit",
    icon: RotateCcw,
    path: "/resit-exams",
    routes: resitRoutes,
    isParent: true,
    children: [
      {
        id: "resit-exam",
        label: "Resit Exam",
        path: "/resit-exams",
        routes: resitRoutes,
      },
      {
        id: "resit-candidate",
        label: "Resit Candidate",
        path: "/resit-candidate",
        routes: resitRoutes,
      },
      {
        id: "resit-timetable",
        label: "Resit Timetable",
        path: "/resit-timetable",
        routes: resitRoutes,
      },
      {
        id: "student-resit",
        label: "Student Resit",
        path: "/student-resit",
        routes: resitRoutes,
      },
    ],
  },
  {
    id: "manage-students",
    label: "Manage Students",
    icon: Users,
    path: "/students",
    routes: StudentRoutes,
    isParent: true,
    children: [
      {
        id: "students",
        label: "Students",
        path: "/students",
        routes: StudentRoutes,
      },
      {
        id: "student-dropouts",
        label: "Student Dropouts",
        path: "/studentDropout",
        routes: StudentRoutes,
      },
      {
        id: "parents",
        label: "Parents",
        path: "/parents",
        routes: StudentRoutes,
      },
      {
        id: "student-batches",
        label: "Student Batches",
        path: "/student-batches",
        routes: StudentRoutes,
      },
    ],
  },
  {
    id: "school-activities",
    label: "School Activities",
    icon: Activity,
    path: "/announcement-overview",
    routes: schoolActivities,
    isParent: true,
    children: [
      {
        id: "announcements",
        label: "Announcements",
        path: "/announcement-overview",
        routes: announcementRoutes,
      },
      {
        id: "elections",
        label: "School Elections",
        path: "/election-overview",
        routes: electionRoutes,
      },
      {
        id: "events",
        label: "School Events",
        path: "/events",
        routes: eventRoutes,
      },
    ],
  },
  {
    id: "finances",
    label: "Finances",
    icon: Wallet,
    path: "/school-expenses",
    routes: financialRoutes,
    isParent: true,
    children: [
      {
        id: "school-expenses",
        label: "School Expenses",
        path: "/school-expenses",
        routes: schoolExpenseRoutes,
      },
      {
        id: "resit-fees",
        label: "Resit Fees",
        path: "/resit-payments",
        routes: resitFeeRoutes,
      },
      {
        id: "tuition-fees",
        label: "Tuition Fees",
        path: "/fee-payments",
        routes: tuitionFeeRoutes,
      },
      {
        id: "registration-fees",
        label: "Registration Fees",
        path: "/registration-fees",
        routes: registrationFeeRoutes,
      },
      {
        id: "additional-fees",
        label: "Additional Fees",
        path: "/additional-fees",
        routes: additionalFeeRoutes,
      },
    ],
  },
  {
    id: "account-activation",
    label: "Account Activation",
    icon: UserPlus,
    path: "/activation-code",
    routes: activationCodeRoutes,
    isParent: false,
  },
];
