export const GRADE_SCALE_COLUMNS = [
  {
    program_name: "grade_title",
    type: "standard_field",
    label: "Grade Title",
    required: true,
    aliases: ["grade_title", "grade_name", "g_title"],
  },
  {
    program_name: "exam_type",
    type: "standard_field",
    label: "Exam Type",
    required: true,
    aliases: ["exam_type", "exam"],
  },
  {
    program_name: "grade_max_score",
    type: "standard_field",
    label: "Grade Max Score",
    required: true,
    aliases: ["grade_max_score"],
  },
  {
    program_name: "max_score",
    type: "standard_field",
    label: "Max Score",
    required: true,
    aliases: ["max_score", "m_score", "maximum_score"],
  },
  {
    program_name: "min_score",
    type: "standard_field",
    label: "Min Score",
    required: true,
    aliases: ["min_score", "m_score", "minimum_score"],
  },
  {
    program_name: "grade",
    type: "standard_field",
    label: "Grade",
    required: true,
    aliases: ["grade", "letter_grade", "l_grade"],
  },
  {
    program_name: "result",
    type: "standard_field",
    label: "Result",
    required: true,
    aliases: ["result"],
  },
  {
    program_name: "resit_result",
    type: "standard_field",
    label: "Resit Result",
    required: true,
    aliases: ["resit_result", "r_result"],
  },
  {
    program_name: "performance",
    type: "standard_field",
    label: "Performance",
    required: true,
    aliases: ["performance", "accredition"],
  },
];
