import { STEPS } from "./stepConstants";
export const STEP_FLOW = [
  STEPS.INTRODUCTION,
  STEPS.DEFAULT_BREAK_PERIOD,
  STEPS.REVIEW_DEFAULT_SCHEDULE,
  STEPS.DAYS_WITHOUT_BREAKS,
  STEPS.CUSTOM_BREAK_DAYS,
  STEPS.REVIEW,
];
