
export const STEPS = {
  INTRODUCTION: "INTRODUCTION",
  DEFAULT_BREAK_PERIOD: "DEFAULT_BREAK_PERIOD",
  REVIEW_DEFAULT_SCHEDULE: "REVIEW_DEFAULT_SCHEDULE",
  DAYS_WITHOUT_BREAKS: "DAYS_WITHOUT_BREAKS",
  EXCEPTION_DAYS: "EXCEPTION_DAYS",
  CUSTOM_BREAK_DAYS: "CUSTOM_BREAK_DAYS",
  REVIEW: "REVIEW",
};
