import jsPDF from "jspdf";

import BaseGenerator from "../BaseGenerator";

import PdfHeader from "./PdfHeader";
import PdfTable from "./PdfTable";
import PdfFooter from "./PdfFooter";

import ExportFormats from "../../constants/ExportFormats";
import FileExtensions from "../../constants/FileExtensions";
import MimeTypes from "../../constants/MimeTypes";

class PdfGenerator extends BaseGenerator {

    /**
     * Generate a PDF document.
     *
     * Payload Structure
     *
     * {
     *   title: "Teachers Report",
     *   subtitle: "Academic Year 2025/2026",
     *   footer: "Generated by Smart School Suite",
     *
     *   columns: [],
     *   rows: []
     * }
     */
    async generate(payload) {

        this.validate(payload);

        const pdf = new jsPDF({
            orientation: "landscape",
            unit: "mm",
            format: "a4",
            compress: true,
        });

        // --------------------------------------------------
        // Render Header
        // --------------------------------------------------

        const startY = PdfHeader.render(pdf, {
            title: payload.title,
            subtitle: payload.subtitle,
            generatedAt: new Date(),
        });

        // --------------------------------------------------
        // Render Table
        // --------------------------------------------------

        PdfTable.render(pdf, {
            startY,
            columns: payload.columns,
            rows: payload.rows,
        });

        // --------------------------------------------------
        // Render Footer
        // --------------------------------------------------

        PdfFooter.render(pdf, {
            footerText:
                payload.footer || "Generated by Smart School Suite",
        });

        // --------------------------------------------------
        // Build File
        // --------------------------------------------------

        const arrayBuffer = pdf.output("arraybuffer");

        return {
            format: ExportFormats.PDF,

            extension: FileExtensions[ExportFormats.PDF],

            mimeType: MimeTypes[ExportFormats.PDF],

            data: new Uint8Array(arrayBuffer),
        };

    }

    /**
     * Validate payload.
     */
    validate(payload) {

        if (!payload) {
            throw new Error("PDF payload is required.");
        }

        if (!Array.isArray(payload.columns)) {
            throw new Error("Columns must be an array.");
        }

        if (!Array.isArray(payload.rows)) {
            throw new Error("Rows must be an array.");
        }

    }

}

export default PdfGenerator;