export const STEPS = {
     INTRODUCTION:"INTRODUCTION",
     ASSIGNMENT_DAYS:"ASSIGNMENT_DAYS",
     ASSIGNMENT_LIST:"ASSIGNMENT_LIST",
     ASSIGNMENT_BUILDER:"ASSIGNMENT_BUILDER",
     REVIEW:"REVIEW"
}