export const STEPS = {
  INTRODUCTION: "INTRODUCTION",
  DEFAULT_HOURS: "DEFAULT_HOURS",
  OPERATING_DAYS: "OPERATING_DAYS",
  REVIEW: "REVIEW",
  EXCEPTION_DAYS: "EXCEPTION_DAYS",
  CONFIGURE_EXCEPTIONS: "CONFIGURE_EXCEPTIONS",
  FINAL_REVIEW: "FINAL_REVIEW",
};
