import  { STEPS } from "./stepConstants";

export const STEP_FLOW = [
    STEPS.INTRODUCTION,
    STEPS.DEFAULT_HOURS,
    STEPS.OPERATING_DAYS,
    STEPS.REVIEW,
    STEPS.EXCEPTION_DAYS,
    STEPS.CONFIGURE_EXCEPTIONS,
    STEPS.FINAL_REVIEW
];