import { STEPS } from "./stepConstants";

export const STEP_FLOW = [
   STEPS.INTRODUCTION,
   STEPS.DEFAULT_PERIOD_DURATION,
   STEPS.REVIEW_WEEKLY_SCHEDULE,
   STEPS.CUSTOM_DURATION_DAYS,
   STEPS.REVIEW  
];