export const STEPS = {
  INTRODUCTION: "INTRODUCTION",
  DEFAULT_PERIOD_DURATION:"DEFAULT_PERIOD_DURATION",
  REVIEW_WEEKLY_SCHEDULE:"REVIEW_WEEKLY_SCHEDULE",
  CUSTOM_DURATION_DAYS:"CUSTOM_DURATION_DAYS",
  REVIEW:"REVIEW"
};